ccflags-y += -Idrivers/media/platform/msm/camera_v2-ulysse
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ulysse/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ulysse/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ulysse/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ulysse/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ulysse/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/ ir_led/ ir_cut/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
