ccflags-y += -Idrivers/media/platform/msm/camera_v2-ulysse
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ulysse/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ulysse/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ulysse/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
