ccflags-y += -Idrivers/media/platform/msm/camera_v2-ulysse
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ulysse/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ulysse/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_ir_cut.o
